  footer: 'This error was generated by Cloudflare on behalf of the website owner.'
}
❌ Kanal [1465058037088784447] hatası: 429 {
  type: 'https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-1xxx-errors/error-1015/',
  title: 'Error 1015: You are being rate limited',
  status: 429,
  detail: "You are being rate-limited by the website owner's configuration.",
  instance: '9f2e66394d87ee28',
  error_code: 1015,
  error_name: 'rate_limited',
  error_category: 'rate_limit',
  ray_id: '9f2e66394d87ee28',
  timestamp: '2026-04-27T14:08:27Z',
  zone: 'discord.com',
  cloudflare_error: true,
  retryable: true,
  retry_after: 30,
  owner_action_required: false,
  what_you_should_do: '**Wait and retry.** This block is transient. Wait at least 30 seconds, then retry with exponential backoff.\n' +
    '\n' +
    'Recommended approach:\n' +
    '1. Wait 30 seconds before your next request\n' +
    '2. If rate-limited again, double the wait time (60s, 120s, etc.)\n' +
    '3. If rate-limiting persists after 5 retries, stop and reassess your request pattern',
  footer: 'This error was generated by Cloudflare on behalf of the website owner.'
}
❌ Kanal [1465052769743405128] hatası: 429 {
  type: 'https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-1xxx-errors/error-1015/',
  title: 'Error 1015: You are being rate limited',
  status: 429,
  detail: "You are being rate-limited by the website owner's configuration.",
  instance: '9f2e66589e91ee28',
  error_code: 1015,
  error_name: 'rate_limited',
  error_category: 'rate_limit',
  ray_id: '9f2e66589e91ee28',
  timestamp: '2026-04-27T14:08:32Z',
  zone: 'discord.com',
  cloudflare_error: true,
  retryable: true,
  retry_after: 30,
  owner_action_required: false,
  what_you_should_do: '**Wait and retry.** This block is transient. Wait at least 30 seconds, then retry with exponential backoff.\n' +
    '\n' +
    'Recommended approach:\n' +
    '1. Wait 30 seconds before your next request\n' +
    '2. If rate-limited again, double the wait time (60s, 120s, etc.)\n' +
    '3. If rate-limiting persists after 5 retries, stop and reassess your request pattern',
  footer: 'This error was generated by Cloudflare on behalf of the website owner.'
}
